2FA Auth Code Generation/Verification
cascaritaco/cascarita pull request #104
Opened 2024-08-06 07:46 UTC by JesusGo115

### Description

Created backend logic to generate a 2FA code sent through mail to verify your account before resetting your password. 

### Testing the Features
**Make sure to do _npm i_ and _run sequelize migrations_**

The route for sending an email and verifying an auth code can be found under "User Auth" on postman. 

You need a **Brevo** account and an api key. In your .env file, add "BREVO_API_KEY=" and your api key here

**Make sure to modify this before testing:**
1. in `user.controller.js,` change the `senderEmail` to your email used for your Brevo account **It will not work otherwise**
2. Within the postman, change `email` within the body tab to the recipient email on both `send email` and `verify auth code` routes

### Things to note

- Email function was moved to the user controller as the function can be used for both sending form links and auth code, depending on the `emailType` (look at the `sendEmail` function within the `user.controller.js` file to view available email formats)
- New table has been added `AuthCode` to keep track of all auth codes so make sure to run migrations

### Checklist

- [x] I have tested the changes locally by running `npm run test`
- [x] I have autoformatted the code by running `npm run eslint`
- [ ] Backend logic to reset the password once the auth code was verified

2024-08-06 15:35 UTC, saulRM10 commented on server/controllers/user.controller.js
> +  var sendEmail = async function (req, res, next) {
Do the forms use this function as well no ? I see you deleted some email function from the forms controller

2024-08-06 16:47 UTC, abanuelo requested changes
Honestly, great job @JesusGo115! Code is clean, readible, and the logic is sound! Just a couple of nits but once those have been resolved happy to approve!

2024-08-06 16:47 UTC, abanuelo commented on server/controllers/user.controller.js
> +  var sendEmail = async function (req, res, next) {
I think when I created it, I added it as part of the forms controller but honestly its pretty independent so feel free to include within the users controller file if it makes sense!

2024-08-06 16:47 UTC, abanuelo commented on server/controllers/user.controller.js
> +      const typeformLink = req.body.formLink || "";
nit: since we already removed all typeform dependencies, maybe rename this to `formLink`? 
```suggestion
      const formLink = req.body.formLink || "";
```

2024-08-06 16:47 UTC, abanuelo commented on server/controllers/user.controller.js
> +      if (!result) {
I see we are storing attempts. Are there any best practices for how to limit the userOpt code entry attempts? Like should we stop it after `x` attempts? If so consider the following suggestion. 
```suggestion
      const MAX_OPT_ATTEMPTS = 5;
      if (!result || userOtp.attempts >= MAX_OPT_ATTEMPTS) {
```

2024-08-06 18:21 UTC, saulRM10 commented on server/controllers/user.controller.js
> +        emailType === "passwordCode" ? await generateOTP() : null;
this generateOTP should not be asynchronous, its a small operation.

2024-08-06 18:27 UTC, saulRM10 requested changes
Left some comments. The generation of emails is using a lot of hardcoded values. What id we add more types of emails ? Also the `sendEmail` is doing a lot , maybe break it up ; `storeCode()` etc..

2024-08-06 21:56 UTC, JesusGo115 commented on server/controllers/user.controller.js
> +  var sendEmail = async function (req, res, next) {
It was originally in the forms controller, like Armando mentioned, but since we plan to send emails with different formats (One for sending form links and another for auth codes), I thought it'd be more appropriate to move it to User controller as it has uses for both forms and user information.

2024-08-07 01:15 UTC, saulRM10 commented on server/controllers/user.controller.js
> +  var sendEmail = async function (req, res, next) {
Makes sense, my concern was if you removed it from the form controller. We can still send form links via email

2024-08-07 01:16 UTC, saulRM10 commented on server/controllers/user.controller.js
> +      const typeformLink = req.body.formLink || "";
agree

2024-08-07 22:16 UTC, JesusGo115 commented on server/controllers/user.controller.js
> +        emailType === "passwordCode" ? await generateOTP() : null;
You right. Changed.

2024-08-07 22:18 UTC, JesusGo115 commented on server/controllers/user.controller.js
> +      const typeformLink = req.body.formLink || "";
Changed.

2024-08-07 22:39 UTC, JesusGo115 commented on server/controllers/user.controller.js
> +      if (!result) {
Added!

2024-08-08 05:35 UTC, saulRM10 commented on server/controllers/user.controller.js
> +  var sendEmail = async function (recipientEmail, subject, emailContent) {
I think we should have this in a try/catch and in the catch throw the error. I see your if statement checking for `response.status` but i think we should know exactly when this third party api fails. Also i see you pass back the responseData but don't use it, another reason to just have a try/catch here in `sendEmail()` if an error occurs it will throw it and whoever called it will know without needed to have an if statement. If email is sent successfully return nothing.

2024-08-08 05:39 UTC, saulRM10 commented on server/controllers/user.controller.js
> +      const response = await sendEmail(recipientEmail, subject, emailContent);
if you add a try/catch in the` sendEmail() ` all you have to do is await that sendEmail to finish up, if no error then function continues to execute. If error with `sendEmail()` your try/catch in **this** function will get hit. Thus eliminating the need to return and store a response from `sendEmail()` and also eliminate the need to do an `if` check one the status

2024-08-08 05:39 UTC, saulRM10 commented on server/controllers/user.controller.js
> +        throw new Error(
throw error in the `sendEmail()`

2024-08-08 05:41 UTC, saulRM10 commented on server/controllers/user.controller.js
> +      const response = await sendEmail(recipientEmail, subject, emailContent);
if you update `sendEmail() `to throw error, no need to store the whole thing in a `response`

2024-08-08 05:48 UTC, saulRM10 commented on server/controllers/user.controller.js
> +      const response = await updateUserById(req, res, next);
A bit confused by this one, you find the user by email with a `User.findOne()` and then call updateUserById where that one does another query with `User.findByPk()`

2024-08-08 05:51 UTC, saulRM10 requested changes
I like that you broke it down, just requesting changes on the way you handle the error in the `sendEmail()` , also left a comment on a function i am confused by: `updateUserByEmail()`

2024-08-08 16:31 UTC, abanuelo requested changes
Added some more review here as well! Great work! It is coming together team!

2024-08-08 16:31 UTC, abanuelo commented on server/controllers/user.controller.js
> +    const apiKey = process.env.BREVO_API_KEY;
nit: can we be specific as to why API Key this is, `brevoAPIKey`?
```suggestion
    const brevoAPIKey = process.env.BREVO_API_KEY;
```

2024-08-08 16:31 UTC, abanuelo commented on server/routes/user.routes.js
> +router.post("/verifyOTP", UserController.verifyOTP);
These don't seem restful. Can we change them to as follows:

```suggestion
router.post("/otp/emails", UserController.sendOtpEmail);
router.post("/forms/emails", UserController.sendFormLinkEmail);
router.post("/otp/verification", UserController.verifyOTP);
```

2024-08-08 21:43 UTC, JesusGo115 commented on server/routes/user.routes.js
> +router.post("/verifyOTP", UserController.verifyOTP);
Changed! Thanks for the heads up!

2024-08-08 21:44 UTC, JesusGo115 commented on server/controllers/user.controller.js
> +    const apiKey = process.env.BREVO_API_KEY;
Changed!

2024-08-09 04:47 UTC, JesusGo115 commented on server/controllers/user.controller.js
> +  var sendEmail = async function (recipientEmail, subject, emailContent) {
Met up with Saul, worked out a solution!

2024-08-09 04:48 UTC, JesusGo115 commented on server/controllers/user.controller.js
> +      const response = await updateUserById(req, res, next);
Removed the updateUserByEmail as it's redundant.

2024-08-09 06:01 UTC, saulRM10 approved these changes
Looks good, great job Chuy !

2024-08-09 17:29 UTC, abanuelo approved these changes
LGTM! Thanks for being thorough with the feedback!

2024-08-09 19:15 UTC, merged