Feature/Home_Workflow
cascaritaco/cascarita pull request #106
Opened 2024-08-07 02:33 UTC by jipatino98

### Description

Created the workflow from League -> Season -> Division -> Team. Included in this PR is also several components that can be used elsewhere in the app. This includes:
- DeleteForm: Allows developers to create modals that warn users they are about to perform a destructive action.
- DropDownMenuButton: Added a more functionality to the existing component by giving developers the option to add their customized item labels
- BreadCrumb: **Still a WIP** React Router may need to be updated to current version so that we can make use of the Native Breadcrumb api (ie `useMatches` and `createBrowserRouter`)
- FileUpload: Allows developers to add drag and drop areas such as the one seen in the Team form (see below) which can be used to upload files to the server

<img width="538" alt="Screenshot 2024-08-06 at 7 31 13 PM" src="https://github.com/user-attachments/assets/cf7a0fca-1dc0-4a05-bb16-efe2ca67dae4">

### Issue Link

https://cascarita.atlassian.net/browse/C1-97

### Checklist

- [x] I have tested the changes locally by running `npm run test`
- [x] I have added or updated relevant documentation
- [x] I have autoformatted the code by running `npm run eslint`
- [x] I have added test cases (if applicable)

### Additional Notes

2024-08-07 18:50 UTC, abanuelo requested changes
Overall amazing work! The amount of code written here is not trivial and is very dense and well layed out. I have a couple of minor cleanup comments but overall this looks amazing! Thanks for hard work here @jipatino98 !

2024-08-07 18:50 UTC, abanuelo commented on client/components/FileUpload/FileUpload.tsx
> +    console.log(acceptedFiles[0]);
nit: remove console logs

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/DivisionForm/DivisionForm.tsx
> +    console.log("Enter handled submit");
nit: remove console logs

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/DivisionForm/services/mutations.ts
> +        console.log(`Error from Update: ${error}`);
```suggestion
        console.error(`Error from Update Division: ${error}`);
```

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/DivisionForm/services/mutations.ts
> +        console.log(`Error from Delete: ${error}`);
```suggestion
        console.error(`Error from Delete Division: ${error}`);
```

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/DivisionForm/services/service.tsx
> +};
Can we move this to the `client/api` folder so we can keep track of all backend APIs easier? The same applies to all other functions that have a `fetch(/api/....)` in this file!

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/LeagueForm/LeagueForm.tsx
> +        await deleteLeagueMutation.mutateAsync({
Just a question here but why is `DELETE` async but the other calls are synchronous? Is that what we want?

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/LeagueForm/services/mutations.ts
> +        console.log(`Error from Update: ${error}`);
```suggestion
        console.error(`Error from Update League: ${error}`);
```

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/LeagueForm/services/mutations.ts
> +        console.log(`Error from Delete: ${error}`);
```suggestion
        console.error`Error from Delete League: ${error}`);
```

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/LeagueForm/services/service.tsx
> +};
Can we also move all these backend functions to the `client/api` folder?

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/LeagueForm/LeagueForm.tsx
> +          <p>{`Are you sure you want to delete?`}</p>
```suggestion
          <p>Are you sure you want to delete?</p>
```

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/SeasonForm/services/mutations.ts
> +        console.log(`Error from Update: ${error}`);
```suggestion
        console.error(`Error from Update Season: ${error}`);
```

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/SeasonForm/services/mutations.ts
> +        console.log(`Error from Delete: ${error}`);
```suggestion
        console.error(`Error from Delete Season: ${error}`);
```

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/SeasonForm/services/services.ts
> +};
Again let's move this to the `client/api` folder.

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/TeamsForm/services/mutations.ts
> +        console.log(`Error from Update: ${error}`);
```suggestion
        console.error(`Error from Update Team: ${error}`);
```

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/TeamsForm/services/mutations.ts
> +        console.log(`Error from Delete: ${error}`);
```suggestion
        console.error(`Error from Delete Team: ${error}`);
```

2024-08-07 18:50 UTC, abanuelo commented on client/components/Forms/TeamsForm/services/service.ts
> +};
Move this to `client/api`

2024-08-07 18:50 UTC, abanuelo commented on client/pages/Division/types.ts
> +  // start_date: Date;
nit: remove these comments

2024-08-07 18:50 UTC, abanuelo commented on client/pages/Forms/Forms.tsx
> +                onClick={() => handleShareClick(form.form_data._links.display)}>
For this I know that @JesusGo115 made some changes to keep only certain parts of the `form_data`. Did you try pulling from `main` and testing this out?

2024-08-07 18:50 UTC, abanuelo commented on client/pages/Home/Home.tsx
> +          {/* <h1> Welcome {currentUser.first_name} </h1> <Leagues /> */}
nit: delete
```suggestion
```

2024-08-07 18:50 UTC, abanuelo commented on client/pages/Seasons/types.ts
> +  // start_date: Date;
nit: delete comments

2024-08-07 18:50 UTC, abanuelo commented on server/controllers/season.controller.js
> +  console.log(league);
nit: remove
```suggestion
```

2024-08-07 18:50 UTC, abanuelo commented on server/controllers/team.controller.js
> +        console.log(session_id);
nit: remove
```suggestion
```

2024-08-07 18:50 UTC, abanuelo commented on server/routes/season.routes.js
> +router.post("/dummy/:division_id/:season_id", SessionController.createSession);
Is there a need to keep this `/dummy` endpoint? Was this just for testing?

2024-08-07 20:56 UTC, jipatino98 commented on client/components/Forms/LeagueForm/LeagueForm.tsx
> +        await deleteLeagueMutation.mutateAsync({
No particular reason, both cases will work in our use case. I went with `mutateAync` because it was recommended by TanStack tutorials to deal with other changes in our app. In this case, however, we probably just need to alert the user through a Banner component or something of a successful or failed deletion. This can be done with just `mutate` so I will change it to that!

2024-08-07 21:10 UTC, jipatino98 commented on client/pages/Forms/Forms.tsx
> +                onClick={() => handleShareClick(form.form_data._links.display)}>
Just fixed, Thanks for the heads up!

2024-08-07 21:15 UTC, jipatino98 commented on server/routes/season.routes.js
> +router.post("/dummy/:division_id/:season_id", SessionController.createSession);
Yes! It was for testing! I will remove promptly. Thanks for the heads up

2024-08-08 16:26 UTC, abanuelo reviewed
Took a second pass look and saw that all comments have been addressed! But for some of the files you created within the `client/api/` folder, they are called, `service.tsx`. Can we rename them to `service.ts`? I don't think they are exporting any react components am I right?

2024-08-09 06:12 UTC, saulRM10 commented on server/controllers/session.controller.js
> +      console.error("sesson with given id does not exist");
we need to do more than just console the error. This will not trigger the `catch(error)` in the functions that calls `getSessionByDivisionAndSeasonId()`  which could trigger other errors if the function that called `getSessionByDivisionAndSeasonId()` continues executing

2024-08-09 06:17 UTC, saulRM10 commented on server/controllers/session.controller.js
> +      console.error("sesson with given id does not exist");
@jipatino98  Here is the issue but i just threw the error to ensure it gets handled !

2024-08-09 17:29 UTC, abanuelo approved these changes
Thanks for addressing my feedback I will approve from my end!

2024-08-09 17:34 UTC, merged