Feat (form builder): Payment Component
cascaritaco/cascarita pull request #116
Opened 2024-08-19 18:32 UTC by elimanzo

## Changes
1. Added Draggable Payment component
2. Added a util function to normalize payment amount (to adjust for Stripe limitations)
3. Added Translations

## Purpose

In preparation for the stripe component when we build the form based off of [figma](https://www.figma.com/design/0RPE1KFkTvkcdvWoYsrxhe/cascarita-logo-ideas?node-id=1515-1275&t=DCVRwbvWljCxKhow-0) designs

![image](https://github.com/user-attachments/assets/d3df3f73-0004-4858-932a-d6081ffc2d03)

### Note
1. When the form is created, there won't be any component for this field (Will be done in another PR)
2. Builder Payment component still needs to be able to retrieve all accounts. (Currently blocked on this)
3. Will eventually need to create a drop down for the currency, but since we're sticking with USD for now, I jut left this as is

2024-08-23 15:57 UTC, abanuelo commented on client/components/DragAndDropComponents/DNDCanvas/DNDCanvas.tsx
> +            price: { type: "fixed", value: "", currency: "USD" },
In the event that we support multiple currencies, can we have USD be an variable?

2024-08-23 15:59 UTC, abanuelo commented on client/components/DragAndDropComponents/DraggablePayment/DraggablePayment.tsx
> +    setIsMenuOpen((prev) => !prev);
Out of curiosity why not just call `setIsMenuOpen(!prev)`?

2024-08-23 16:00 UTC, abanuelo commented on client/components/DragAndDropComponents/DraggablePayment/DraggablePayment.tsx
> +              style={{
Can we push all in-line styling to the relevant `*.module.css`? Better for readability and configurability later down the line!

2024-08-23 16:01 UTC, abanuelo commented on client/components/DragAndDropComponents/DraggablePayment/DraggablePayment.tsx
> +                <option value="">Select an Account</option>
use a map here? I know this is going to change but just make it cleaner

2024-08-23 16:03 UTC, abanuelo commented on client/pages/NewForm/NewForm.tsx
> +    if (formId == null) {
change to `!formId`

2024-08-23 16:04 UTC, abanuelo commented on client/util/formatPayment.ts
> +export const formatPayment = (value: string) => {
I am generally against having oneoff util files unless absolutely necessary. I would say for this case, let's ahead and couple this to where it is being applied within the `DraggablePayment` component?

2024-08-23 16:05 UTC, abanuelo requested changes
Overall very good work and great scaffolding so that we can plug and play new features as they get released into the code base. A couple of nits that I would advise you to take care of so that we can get the ball moving!

2024-08-23 17:25 UTC, elimanzo commented on client/components/DragAndDropComponents/DNDCanvas/DNDCanvas.tsx
> +            price: { type: "fixed", value: "", currency: "USD" },
Hey @abanuelo can you provide a bit of clarity here. I used `currency` as the variable that could be changed later on.

2024-08-23 17:25 UTC, elimanzo commented on client/components/DragAndDropComponents/DraggablePayment/DraggablePayment.tsx
> +              style={{
ack!

2024-08-23 17:26 UTC, elimanzo commented on client/components/DragAndDropComponents/DraggablePayment/DraggablePayment.tsx
> +                <option value="">Select an Account</option>
ack!

2024-08-23 17:48 UTC, elimanzo commented on client/util/formatPayment.ts
> +export const formatPayment = (value: string) => {
> I am generally against having oneoff util files unless absolutely necessary. I would say for this case, let's ahead and couple this to where it is being applied within the `DraggablePayment` component?

So, I mentioned this in the a standup, but there's a possibility to allow the user to input their own amount if the form had the stripe as some optional donation, so this function would be used for that case, and we can avoid coupling. 

As for having one off util, I prefer breaking up logic like this into separate files / function, it makes components a bit more easier to read.

If you don't see this being used in the future I could add to `DraggablePayment` component

2024-08-27 03:58 UTC, abanuelo commented on client/components/DragAndDropComponents/DNDCanvas/DNDCanvas.tsx
> +            price: { type: "fixed", value: "", currency: "USD" },
My rationale here @elimanzo is to eventually have currency tied to some of our stripe tables so we can keep track of internal auditing. This being hardcoded for now is totally fine but just as we consider scaling it might be a nice to have. I will accept as is for now!

2024-08-27 03:58 UTC, abanuelo commented on client/pages/NewForm/NewForm.tsx
> +    if (formId == null) {
Ah gotcha! It's a catch all! Thanks for the thorough explanation!

2024-08-27 03:59 UTC, abanuelo commented on client/util/formatPayment.ts
> +export const formatPayment = (value: string) => {
Let's keep for now but consider dragging into the component later on!

2024-08-27 03:59 UTC, abanuelo approved these changes
LGTM! Thanks for being thorough with the changes and responding to feedback as needed!

2024-08-27 04:23 UTC, elimanzo commented on client/components/DragAndDropComponents/DNDCanvas/DNDCanvas.tsx
> +            price: { type: "fixed", value: "", currency: "USD" },
I'm still a little confused haha, but maybe in a meeting we can discuss it a bit more 😃 .

2024-08-27 04:24 UTC, merged