feat: adding Auth0
cascaritaco/cascarita pull request #119
Opened 2024-09-21 19:55 UTC by abanuelo

### Description

POC of pull request working to integrate Auth0 service directly into cascarita to handle (a) session management, (b) authn and (c) authz, although this is a longer requested change we will implement in future versions of our app!

### Issue Link

### Checklist

- [ ] I have tested the changes locally by running `npm run test`
- [ ] I have added or updated relevant documentation
- [ ] I have autoformatted the code by running `npm run eslint`
- [ ] I have added test cases (if applicable)

### Additional Notes

2024-10-19 23:38 UTC, elimanzo requested changes
Thanks for the PR! I have a few comments about some of these changes, and I think it's good to go.

2024-10-19 23:38 UTC, elimanzo commented on client/api/users/service.ts
> +      logoUrl: data.logoUrl,
I believe we can [spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) here fort his object

```suggestion
      ...data
```

2024-10-19 23:38 UTC, elimanzo commented on client/auth_config.json
> +    "audience": "https://dev-2vszya8j41e1n3fe.us.auth0.com/api/v2/"
Just a quick question. These aren't secrets we need to hide right?

2024-10-19 23:38 UTC, elimanzo commented on client/components/Forms/DivisionForm/DivisionForm.tsx
> +  const currentUser = user;
I don't think  we need another intermediate variable for `user` Maybe just change everything that depends on `currentUser` to just `user`

2024-10-19 23:38 UTC, elimanzo commented on client/components/Forms/LeagueForm/LeagueForm.tsx
> +  const currentUser = user;
same comment as above :)

2024-10-19 23:38 UTC, elimanzo commented on client/components/RegistrationModal/RegistrationModal.tsx
> +  const [selectedOrg, setSelectedOrg] = useState<string>("");
TS can already infer its type so it won't be needed. Also since  this logic is dependent on submitting a form consider using [useReducer](https://react.dev/reference/react/useReducer)


```suggestion
  const [page, setPage] = useState(1);
  const [isExistingOrg, setisExistingOrg] = useState("No");
  const [org, setOrg] = useState("");
  const [address, setAddress] = useState("");
  const [city, setCity] = useState("");
  const [state, setState] = useState("");
  const [zipCode, setZipCode] = useState("");
  const [selectedOrg, setSelectedOrg] = useState("");
```

2024-10-19 23:38 UTC, elimanzo commented on client/components/SelectMenu/SelectMenu.tsx
> +      required={required ? true : false}>
I would recommend to change this variable to `isRequired,` and using [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing)
```suggestion
      required={required ?? false}>
```

2024-10-19 23:38 UTC, elimanzo commented on client/index.tsx
> +const config = getConfig();
is the `getConfig()` being used anywhere else in the code base? if not we can remove the export, and a super pro move is to make it to an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE). if we are then we can leave it as is :)

2024-10-19 23:38 UTC, elimanzo commented on client/pages/Home/Home.tsx
> +          }
```suggestion
          setRegistered(response?.isSigningUp ?? false);

```

2024-10-19 23:38 UTC, elimanzo commented on client/pages/Leagues/Leagues.tsx
> +  // const currentUser = {};
we can  remove this if we don't need it :)

2024-10-19 23:38 UTC, elimanzo commented on client/pages/NewForm/NewForm.tsx
> +  } as User;
little confused on why we need an `emptyUser` here and reassigning `currentUser`?

2024-10-19 23:38 UTC, elimanzo commented on server/controllers/group.controller.js
> +  var getAllGroups = async function (req, res, next) {
I never really understood why our server uses `var`. We should start using `let` / `const`. But this can be done in a different PR to refactor this, since it's all over the servers codebase.

2024-10-19 23:38 UTC, elimanzo commented on server/utilityFunctions/auth0.js
> +      "https://dev-2vszya8j41e1n3fe.us.auth0.com/userinfo",
is this a constant that we're always going to be using? Maybe make it to an env variable?

2024-10-21 04:37 UTC, abanuelo commented on client/auth_config.json
> +    "audience": "https://dev-2vszya8j41e1n3fe.us.auth0.com/api/v2/"
Recommended action to make these environment variables but no they are not secrets. See thread here for details: https://community.auth0.com/t/safe-management-of-auth0-information-in-source-control/19051/3

2024-10-21 05:23 UTC, abanuelo commented on client/api/users/service.ts
> +      logoUrl: data.logoUrl,
Perfect use of spread actually! Thank you!

2024-10-21 05:26 UTC, abanuelo commented on client/components/Forms/DivisionForm/DivisionForm.tsx
> +  const currentUser = user;
Done! On top of that we don't want to use the `user` from the `useAuth0` since these user types are Auth0's user type. We have our own concept of User where `group_id` is in our schema (as you are aware!). I will document this change but this PR assumes Auth0 will handle tracking user's email, picture, roles, etc but the internal business logic (ie group_id user language preference), is all handled by us.

2024-10-21 05:26 UTC, abanuelo commented on client/components/Forms/LeagueForm/LeagueForm.tsx
> +  const currentUser = user;
Applied changes!

2024-10-21 05:28 UTC, abanuelo commented on client/components/SelectMenu/SelectMenu.tsx
> +      required={required ? true : false}>
Done! Thanks for teaching me something new!

2024-10-21 05:42 UTC, abanuelo commented on client/components/RegistrationModal/RegistrationModal.tsx
> +  const [selectedOrg, setSelectedOrg] = useState<string>("");
Done! Thank you for the knowledge! Also implemented `useReducer` alternative to form ingestion!

2024-10-21 05:46 UTC, abanuelo commented on client/pages/Home/Home.tsx
> +          }
Did not use nullish coalescing here since there is some backend logic we need to implement. Reason being: If the `isSigningUp` key is in the response body, it will assume its value as `true` which in case sets the `setRegistered` state to true which hides the modal. There are only two values for this state at the moment (true or undefined). I think for now we need to consider how we can reimplement this but for the time being will optimize it with ternary operator!

2024-10-21 05:48 UTC, abanuelo commented on client/pages/Leagues/Leagues.tsx
> +  // const currentUser = {};
Done! But I am glad I commented this out and not removed because we actually want to be able to reference the current logged in user and fetch their group_id so that when Leagues are created with the LeagueModal, they can be properly seen and displayed them on the table!

2024-10-21 05:49 UTC, abanuelo commented on client/pages/NewForm/NewForm.tsx
> +  } as User;
Temporary changes needed to resolve some errors when debugging auth0! Thanks for catching, I have removed this `emptyUser`.

2024-10-21 05:49 UTC, abanuelo commented on server/utilityFunctions/auth0.js
> +      "https://dev-2vszya8j41e1n3fe.us.auth0.com/userinfo",
On it!

2024-10-21 05:51 UTC, abanuelo commented on server/controllers/group.controller.js
> +  var getAllGroups = async function (req, res, next) {
Agreed! Issued created here: https://github.com/cascaritaco/cascarita/issues/132

2024-10-21 05:57 UTC, abanuelo commented on client/index.tsx
> +const config = getConfig();
Done! Made this into an IIFE and removed the export!

2024-10-21 06:48 UTC, elimanzo commented on client/components/RegistrationModal/RegistrationModal.tsx
> +              <button style={{ marginTop: "26px" }}>Finish</button>
Not sure if you had a preference to use `className` vs inline `style` for this button margin

2024-10-21 06:54 UTC, elimanzo commented on client/pages/Leagues/Leagues.tsx
> +  const [groupId, setGroupId] = useState(null);
I  believe here we do need to set a type because in line 44, it will error if it sets anything other than null.

```suggestion
  const [groupId, setGroupId] = useState<number | null>(null);
```

2024-10-21 20:49 UTC, jipatino98 commented on client/components/Forms/LeagueForm/LeagueForm.tsx
> +import React, { useEffect } from "react";
Yeah, I can fix that! I'll get that addressed asap

2024-10-22 02:54 UTC, abanuelo commented on client/components/Forms/LeagueForm/LeagueForm.tsx
> +import React, { useEffect } from "react";
@jipatino98 I will leave this to you!

2024-10-22 02:54 UTC, abanuelo commented on client/components/RegistrationModal/types.ts
> +  isExistingOrg: string;
Done!

2024-10-22 02:55 UTC, abanuelo commented on client/components/RegistrationModal/types.ts
> +  | { type: "SET_FIELD"; field: keyof State; value: string | number }
Done!

2024-10-22 02:55 UTC, abanuelo commented on client/pages/Leagues/Leagues.tsx
> +  const [groupId, setGroupId] = useState(null);
Done!

2024-10-22 02:55 UTC, abanuelo commented on client/components/RegistrationModal/RegistrationModal.tsx
> +              <button style={{ marginTop: "26px" }}>Finish</button>
Done!

2024-10-22 04:08 UTC, merged