WIP - Stripe Form
cascaritaco/cascarita pull request #120
Opened 2024-09-23 17:36 UTC by elimanzo

### Description

### Issue Link

### Checklist

- [ ] I have tested the changes locally by running `npm run test`
- [ ] I have added or updated relevant documentation
- [ ] I have autoformatted the code by running `npm run eslint`
- [ ] I have added test cases (if applicable)

### Additional Notes

2024-09-29 08:55 UTC, elimanzo commented
@saulRM10 Seems like I got a payment intent to succeed, not sure if you want to 2x your Stripe account to confirm. I believe all we need is

1. An API to fetch the stripe public key
2. An API to fetch all stripe customer accounts (should be a list of stripe ids?)
3. An API to fetch the `userId` from `UserStripeAccounts` SQL table
4. An API to fetch the `form_id` from our SQL table

### Successful payment intent

![image](https://github.com/user-attachments/assets/c51896e8-a770-4052-8046-9bcba56d92aa)

#### I also added a fee field to input the fees
![3fb9f2022a51607a7a1323291dd05bae](https://github.com/user-attachments/assets/bccf39d2-e01d-4566-b91c-9d72faa67c2b)

2024-10-06 00:35 UTC, elimanzo commented
@saulRM10 

I'm getting an issue deleting the form after creating a payment intent, it's getting a query error

![image](https://github.com/user-attachments/assets/bc36f771-9994-4bb2-9bd7-82aec7192406)

![image](https://github.com/user-attachments/assets/81c13ba4-cf34-4154-b992-ba133c14af77)

2024-10-06 05:38 UTC, saulRM10 commented on client/components/Stripe/StripeConnectButton.tsx
> +const ConnectWithStripeButton = ({
@jipatino98  with your current work that was merged in main, we no longer need this button and components for the stripe button, right ? Can we just remove and delete the files ?

2024-10-06 05:48 UTC, saulRM10 commented on client/api/stripe/service.ts
> +    return data.map((account: unknown) => StripeAccountSchema.parse(account));
I see the object is just id, stripe id and first name. Is this what gets used to populate the dropdown option in the payment component ? Should we provide the `platform_account_name` over just the name of the creator of the account ?

2024-10-06 06:11 UTC, elimanzo commented on client/api/stripe/service.ts
> +    return data.map((account: unknown) => StripeAccountSchema.parse(account));
It depends on what you want the list to consist of, the `platform_account_name` or the `first_name`

2024-10-06 06:14 UTC, elimanzo commented on client/components/Stripe/StripeConnectButton.tsx
> +const ConnectWithStripeButton = ({
Yeah I was thinking that we wouldn't need it until I thought that if the user didn't have an account to the group then I should render the button like below 

![image](https://github.com/user-attachments/assets/294bcc58-13c8-4ae6-ba24-903ff0c6befd)

2024-10-07 05:12 UTC, elimanzo commented on client/components/Stripe/StripeConnectButton.tsx
> +const ConnectWithStripeButton = ({
I have the user get directed to the page that @jipatino98 created

![image](https://github.com/user-attachments/assets/4614b34e-e7e1-4375-87bd-fb42661534d5)

2024-10-08 00:25 UTC, jipatino98 reviewed
Took a look and everything looks good. I haven't used ZOD or the null utility so Im excited to look into it. I made some nitpick comments about using the `rem` unit for font sizing in some CSS files.

2024-10-08 00:25 UTC, jipatino98 commented on client/components/DragAndDropComponents/DraggablePayment/DraggablePayment.module.css
> +  font-size: 16px;
Just nitpicking but when it comes to font sizes, i encourage sticking to `rem` units because it allows for better accessibility if the user changes their default font size (16px).
In this cases 1rem = 16px

2024-10-08 02:38 UTC, abanuelo requested changes
Overall great work, a couple of nits and you have my approval!

2024-10-08 02:38 UTC, abanuelo commented on client/api/stripe/service.ts
> +    if (!response.ok) {
nit: seems like a different error here. We are catching the error but if we receive a non `ok` response status, maybe throw a different error

2024-10-08 02:38 UTC, abanuelo commented on client/api/stripe/service.ts
> +    return data.map((account: unknown) => StripeAccountSchema.parse(account));
account type of unknown? What can we expect here?

2024-10-08 02:38 UTC, abanuelo commented on client/components/DragAndDropComponents/DNDCanvas/DNDCanvas.tsx
> +              currency: "USD",
nit: make `USD` an enum since more currencies will potentially be included later

2024-10-08 02:38 UTC, abanuelo commented on client/components/DragAndDropComponents/DraggablePayment/DraggablePayment.tsx
> +  const calculateStripeFee = (price: number): number => {
Why do we need to calculate the fee? Does Stripe not expose an API we can leverage instead of doing the calculations ourselves?

2024-10-08 02:38 UTC, abanuelo commented on client/components/DragAndDropComponents/DraggablePayment/DraggablePayment.tsx
> +                              field.onChange(JSON.parse(e.target.value))
Just being careful here, can we always expect JSON type? No errors being caught so can break our application!

2024-10-08 02:38 UTC, abanuelo commented on client/components/FormInputComponents/Stripe/StripeComponent.tsx
> +  const [options, setOptions] = useState<StripeElementsOptions | undefined>(
why make this `undefined` rather than `null`? Should we be consistent or mindful of which NONE type to work with?

2024-10-08 02:38 UTC, abanuelo commented on client/pages/FormPage/FormPage.tsx
> +        if (!success) {
If the success fails do we want to handle anything here? A simple return seems too nonchalant.

2024-10-08 02:38 UTC, abanuelo commented on client/pages/NewForm/NewForm.tsx
> +        type: toSnakeCase(field.type) as FieldType,
I love that we have our helper functions but this seems like a npm dependency we can rely on but let's keep this for now! Just thinking about the build vs buy tradeoffs given our small engineering team

2024-10-08 03:13 UTC, elimanzo commented on client/api/stripe/service.ts
> +    return data.map((account: unknown) => StripeAccountSchema.parse(account));
I agree! I don't know what we expect here hence the `unknown` 😂 . I'll try and come up with a type to be more safe.

2024-10-08 03:17 UTC, elimanzo commented on client/components/DragAndDropComponents/DraggablePayment/DraggablePayment.tsx
> +  const calculateStripeFee = (price: number): number => {
I wasn't able to find an API to fetch fees, but this was made to show transparency with customers if they're paying the fee or the org is.

2024-10-08 03:58 UTC, elimanzo commented on client/components/DragAndDropComponents/DraggablePayment/DraggablePayment.module.css
> +  font-size: 16px;
Good to know Thank!

2024-10-08 04:07 UTC, elimanzo commented on client/api/stripe/service.ts
> +    if (!response.ok) {
ack!

2024-10-08 04:10 UTC, elimanzo commented on client/components/DragAndDropComponents/DNDCanvas/DNDCanvas.tsx
> +              currency: "USD",
ack!

2024-10-08 04:12 UTC, elimanzo commented on client/components/FormInputComponents/Stripe/StripeComponent.tsx
> +  const [options, setOptions] = useState<StripeElementsOptions | undefined>(
going off of stripe's API the option prop can only be `(property) ElementsProps.options?: StripeElementsOptions | undefined`

2024-10-08 04:23 UTC, elimanzo commented on client/components/DragAndDropComponents/DraggablePayment/DraggablePayment.tsx
> +                              field.onChange(JSON.parse(e.target.value))
yea I agree, I'll write a `try-catch` block here and if it breaks, it will reset to the default account.

I think passing an a `stripe_account_id` and a `table_id` is pretty redundant, maybe in another PR we can refactor it where we should depend both of these ids to render the form. I'll tag @saulRM10 for this :)

2024-10-08 04:40 UTC, elimanzo commented on client/pages/FormPage/FormPage.tsx
> +        if (!success) {
[`handlePayment()`](https://github.com/cascaritaco/cascarita/pull/120/files#diff-2240fb91befc97b98b01082c05c0fc0edea44c8bc62217762e84b88eeef9b86aR12-R34) is already handling the error under the stripe form. Returning here just prevents the form from being submitted.

2024-10-08 04:50 UTC, elimanzo commented on client/api/stripe/service.ts
> +    return data.map((account: unknown) => StripeAccountSchema.parse(account));
I made the this api call now consumes everything. I was going to put down the platform account but it can be null and it was a little weird seeing no account name for the drop down haha

2024-10-09 02:50 UTC, abanuelo commented on client/components/DragAndDropComponents/DraggablePayment/DraggablePayment.tsx
> +  const calculateStripeFee = (price: number): number => {
Created isssue #125 for future reference

2024-10-09 02:54 UTC, abanuelo approved these changes
LGTM. All previous feedback I had commented on has been addressed. Approving this PR! And discussed with @saulRM10 that cascading delete error will be handled in a seperate PR!

2024-10-09 03:10 UTC, merged