Feat/Create Junction Table UserRoles
cascaritaco/cascarita pull request #158
Opened 2024-11-21 08:09 UTC by JesusGo115

### Description

This pull request will add a new junction table, UserRoles, that will allow users to have multiple roles using the user ID

### Checklist

- [x] I have tested the changes locally by running `npm run test`
- [ ] I have added or updated relevant documentation
- [ ] I have autoformatted the code by running `npm run eslint`
- [ ] I have added test cases (if applicable)

2024-11-26 06:12 UTC, abanuelo approved these changes
🚀 Thanks for making these changes!

2024-11-30 20:43 UTC, saulRM10 requested changes
Found a potential issue on the `down()` of one of your migrations. Quick fix tho. Besides that, great job chuy !

2024-11-30 20:43 UTC, saulRM10 commented on server/migrations/20241120060820-update-user-table-remove-role-id-column.js
> +        allowNull: false,
This might break, it add back the `role_id` column but `allowNull` is still false. So youd' need to add a default `role_id` so it doesn't break and shoot the sequalize validation error. Id recommend just leaving it as `allowNull: true`

2024-12-04 05:49 UTC, JesusGo115 commented on server/migrations/20241120060820-update-user-table-remove-role-id-column.js
> +        allowNull: false,
Implemented the change. Thanks for spotting that!

2024-12-04 06:30 UTC, saulRM10 reviewed
Thanks for the fix, we have a user (Maria, from salinas soccer femenil) I think in the migration we need to assign any user in our db to `admin` so you will need to add a part in your migration that adds entries to the `UserRoles` table. What do you think @garcialuis @abanuelo

2024-12-04 07:09 UTC, JesusGo115 commented
We could create a migration that sets up a UserRole row as "admin" for every existing user in the User table

2024-12-04 07:15 UTC, saulRM10 commented
> We could create a migration that sets up a UserRole row as "admin" for every existing user in the User table

Can you add a migration for this on this pr ?

2024-12-05 08:41 UTC, JesusGo115 commented
No

2024-12-05 08:41 UTC, JesusGo115 commented
Jk

Yes, I added it. Please take a look!

2025-01-10 03:52 UTC, saulRM10 approved these changes
Looks good Chuy, thanks for adding the migrations that updates the users

2025-01-10 04:15 UTC, merged