feat: Created Language table and added a column to User table to associate with the Language table
cascaritaco/cascarita pull request #56
Opened 2024-05-15 05:55 UTC by JesusGo115

### Description

### Issue Link

### Checklist

- [ ] I have tested the changes locally by running `npm run test`
- [ ] I have added or updated relevant documentation
- [ ] I have autoformatted the code by running `npm run eslint`
- [ ] I have added test cases (if applicable)

### Additional Notes

2024-05-15 15:54 UTC, abanuelo approved these changes
This looks great. One thing I had a question on @JesusGo115 is are we going to add the controller methods directly in this PR so I can call on the Language Table? If so, it might be helpful to couple those changes inside this PR as well.

2024-05-15 18:53 UTC, saulRM10 requested changes
Another thing is that this pr is branched off your branch team controller , base branch should be `main`  right ? I think you should be good to rebase. Also the user controller needs the updated logic about the language field. Also a function to handle the updating of the language preference

2024-05-15 23:06 UTC, saulRM10 commented on server/controllers/season.controller.js
> +      res.json(teamSession);
you will not be returning status code for this function ?

2024-05-16 05:12 UTC, JesusGo115 commented on server/controllers/season.controller.js
> +      res.json(teamSession);
Fixed this.

2024-05-16 05:39 UTC, abanuelo requested changes
Almost done! Great work!

2024-05-16 05:39 UTC, abanuelo commented on server/routes/user.routes.js
> +router.patch("/:id", UserController.updateLanguagePreference);
Make this (a) POST and (b) /:id/languages so we know that its tied to language specific updates

2024-05-16 05:39 UTC, abanuelo commented on server/controllers/user.controller.js
> +      currentUser.language_id = req.body.language_id || currentUser.language_id;
Why are we adding this `||`? Is it in case the language_id is not added to the request body and so we default to the original setting for the language_id?

2024-05-16 05:39 UTC, abanuelo commented on server/controllers/user.controller.js
> +      let currentUser = await User.findOne({
You are using `.findOne` here but in the `getLanguageByUserId` you use `.findByPk`. Let's stick with `.findByPk` for both methods.

2024-05-16 05:39 UTC, abanuelo commented on server/controllers/user.controller.js
> +      let currentUser = await User.findOne({
Also let's keep error messages the same as well!

2024-05-16 05:39 UTC, abanuelo commented on server/__tests__/routeTests/user.routes.test.js
> +  it.each(fields)(
Can we add a test case updating the language preference just to make sure that works!

2024-05-17 20:38 UTC, JesusGo115 commented on server/controllers/user.controller.js
> +      currentUser.language_id = req.body.language_id || currentUser.language_id;
Yeah, it's to make sure that the input is not an invalid value or if the language id doesn't exist within the language table

2024-05-17 20:43 UTC, JesusGo115 commented on server/controllers/user.controller.js
> +      let currentUser = await User.findOne({
Updated the function with the findByPK and updated the error messages 👍

2024-05-17 21:24 UTC, JesusGo115 commented on server/routes/user.routes.js
> +router.patch("/:id", UserController.updateLanguagePreference);
Updated the methods with post and the route name!

2024-05-20 02:03 UTC, JesusGo115 commented on server/__tests__/routeTests/user.routes.test.js
> +  it.each(fields)(
Added the test!

2024-05-20 18:45 UTC, abanuelo requested changes
Almost done! Just one minor nit!

2024-05-20 18:45 UTC, abanuelo commented on server/routes/user.routes.js
> +router.get("/:id/languages", UserController.getLanguageByUserId);
nit: Can we make this `language` instead of `languages`. Let's keep with the RESTful singular expression thanks @JesusGo115 :)

2024-05-20 18:50 UTC, saulRM10 requested changes

2024-05-20 18:50 UTC, saulRM10 commented on server/models/team.js
> +            msg: "Name field is required",
the `msg` should all be lowercase since we want to keep error messages all lowercase

2024-05-20 18:50 UTC, saulRM10 commented on server/models/user.js
> +            msg: "First name field is required",
make sure `msg` are all lowercase

2024-05-20 18:50 UTC, saulRM10 commented on server/routes/team.routes.js
> +router.get("/group/:id", TeamController.getTeamByGroupId);
all this team stuff is coming from you branches off your team branch ?

2024-05-20 18:50 UTC, saulRM10 commented on server/__tests__/controllerTests/user.controller.test.js
> +describe.skip("registerUser UNUSED", () => {
i think instead of skipping we can just delete the file ? Since we are doing integration testing with the routes not much need for this file @abanuelo ?

2024-05-20 18:50 UTC, saulRM10 commented on server/controllers/teamSession.controller.js
> +const { TeamsSession } = require("../models");
make sure error messages are all lowercase

2024-05-20 18:50 UTC, saulRM10 commented on server/controllers/team.controller.js
> +const TeamsSessionController = require("../controllers/teamSession.controller");
make sure error messages are all lowercase

2024-05-20 18:50 UTC, saulRM10 commented on server/controllers/user.controller.js
> +  var getLanguageByUserId = async function (req, res, next) {
make sure error messages are all lowercase

2024-05-20 19:12 UTC, saulRM10 commented on server/controllers/user.controller.js
> +      return res.json(user.language_id);
lets just return the the whole user but exclude the password attribute

2024-05-20 19:45 UTC, JesusGo115 commented on server/routes/user.routes.js
> +router.get("/:id/languages", UserController.getLanguageByUserId);
I believe it's restful to make the expression as plural, que no? I talked to Leo about it and to remain RESTful, there shouldn't be any singular words.

2024-05-20 19:54 UTC, JesusGo115 commented on server/__tests__/controllerTests/user.controller.test.js
> +describe.skip("registerUser UNUSED", () => {
Deleted the file

2024-05-20 19:54 UTC, JesusGo115 commented on server/controllers/teamSession.controller.js
> +const { TeamsSession } = require("../models");
Changed all the error messages to lowercase for teams and teamsSession

2024-05-20 19:55 UTC, saulRM10 commented on server/migrations/20240515052722-update-users-table-add-column-lang.js
> +        onDelete: "CASCADE",
on delete this should be set to default English language  ? At the moment if you delete a langue that is used by a User that user will be deleted

2024-05-27 20:40 UTC, JesusGo115 commented on server/routes/team.routes.js
> +router.get("/group/:id", TeamController.getTeamByGroupId);
I updated and did all team stuff in this PR since I pulled them in by accident. Will most likely delete the other PR as a result of this.

2024-05-27 20:41 UTC, JesusGo115 commented on server/migrations/20240515052722-update-users-table-add-column-lang.js
> +        onDelete: "CASCADE",
I updated to be RESTRICTED for both so it can prevent that.

2024-05-27 21:47 UTC, JesusGo115 commented on server/models/team.js
> +            msg: "Name field is required",
Updated the messages

2024-05-28 01:34 UTC, abanuelo approved these changes
LGTM

2024-05-28 01:38 UTC, saulRM10 commented on server/__tests__/controllerTests/teamsSession.controller.test.js
> +
remove console logs in tests

2024-05-28 01:38 UTC, saulRM10 commented on server/__tests__/controllerTests/teamsSession.controller.test.js
> +
remove console logs

2024-05-28 01:39 UTC, saulRM10 approved these changes
just remove console logs

2024-05-28 01:53 UTC, JesusGo115 commented on server/__tests__/controllerTests/teamsSession.controller.test.js
> +
Removed the console logs

2024-05-28 02:57 UTC, merged