Feat: Added Form Builder Responses
cascaritaco/cascarita pull request #76
Opened 2024-06-09 22:34 UTC by elimanzo

### Description

### Issue Link

### Checklist

- [ ] I have tested the changes locally by running `npm run test`
- [ ] I have added or updated relevant documentation
- [ ] I have autoformatted the code by running `npm run eslint`
- [ ] I have added test cases (if applicable)

### Additional Notes

2024-06-10 22:28 UTC, abanuelo requested changes
Overall great work! Some minor nits and future work items as we continue to scale the frontend of our app! Thanks for making these needed changes!

2024-06-10 22:28 UTC, abanuelo commented on client/components/FormResponses/FormResponses.tsx
> +        const fetchSurveyData = async (endpoint: string) => {
Can we move define this function within the `client/api` folder and import the function into the component?

2024-06-10 22:28 UTC, abanuelo commented on client/components/FormResponses/FormResponses.tsx
> +        <div style={{ display: "flex", justifyContent: "center", padding: 10 }}>
nit: can we add this styling within the `.module.css` file.

2024-06-10 22:28 UTC, abanuelo commented on client/components/FormResponses/FormResponses.tsx
> +  const trimText = (text: string, maxLength: number) => {
Very useful for some of our future frontend components. Can we think about storing this function elsewhere and importing it into the component? I can see if useful for some of the table views we will have!

2024-06-10 22:28 UTC, abanuelo commented on client/components/FormResponses/FormResponses.tsx
> +        answer.file_url ? <a href={answer.file_url}>File</a> : "",
nit: File here can it also be bilingual?

2024-06-10 22:28 UTC, abanuelo commented on client/components/FormResponses/types.ts
> +  date?: string;
Can we stay consistent with backend to frontend types. Like here for instance date is a string when it really should be a timestamp type!

2024-06-10 22:28 UTC, abanuelo commented on client/components/FormResponses/types.ts
> +  hidden: Record<string, unknown>;
nit: why do we need an `unknown` type here?

2024-06-10 22:28 UTC, abanuelo commented on client/pages/Forms/Forms.tsx
> +                    form.welcome_screens[0].properties.description,
Since we are indexing here, is there any risk of `form.welcome_screens` being an empty array? If so this can break! Maybe add some checks for this!

2024-06-10 22:28 UTC, abanuelo commented on client/pages/NewForm/NewForm.tsx
>          edittedBy: currentUser?.first_name ?? "",
nit: should this be `editedBy` instead of `edittedBy`?

2024-06-10 22:28 UTC, abanuelo commented on client/pages/NewForm/NewForm.tsx
>        localStorage.setItem("surveys", JSON.stringify(surveys));
nit: Maybe we can make a new issue on this, but I see that we have some reliance on localStorage variables and if this continues to grow, we need to locate at different places in our code to keep track what is being set where. Let's consider making a `localStorage.ts` file where we keep all references to setting localStorage variables and values, etc. Also once we logOut maybe we should consider unsetting them within that same file!

2024-06-10 22:28 UTC, abanuelo commented on client/pages/NewForm/NewForm.tsx
> +        <div className={styles.newFormHeader} style={{}}>
nit: remove `style`

2024-06-10 22:28 UTC, abanuelo commented on client/pages/NewForm/NewForm.tsx
> +            style={{ marginRight: 20 }}
nit: add that style within the className

2024-06-10 22:28 UTC, abanuelo commented on client/pages/NewForm/NewForm.tsx
> +              <p className={styles.smallText} style={{ paddingTop: 8 }}>
nit: add style to className

2024-06-11 04:29 UTC, elimanzo commented on client/pages/NewForm/NewForm.tsx
>        localStorage.setItem("surveys", JSON.stringify(surveys));
Local storage is a temp fix for storing the forms created by user. The is currently being worked on by the backend, to be able to store and fetch forms created by users / groups.

I will create an issue for now. 👍🏽

2024-06-11 04:37 UTC, elimanzo commented on client/components/FormResponses/types.ts
> +  hidden: Record<string, unknown>;
Hidden fields are custom data you can pass to Typeform responses, such as user IDs, session IDs, or other metadata that you want to keep track of. Since these fields can depend on the specific form and use case I resorted to using `unknown`.

2024-06-12 04:42 UTC, abanuelo requested changes
Great work on addressing all the comments! Approving on my end!

2024-06-12 04:42 UTC, abanuelo commented on client/components/FormResponses/types.ts
> +  hidden: Record<string, unknown>;
Got you @elimanzo this makes sense to me!

2024-06-12 04:42 UTC, abanuelo commented on client/pages/NewForm/NewForm.tsx
>        localStorage.setItem("surveys", JSON.stringify(surveys));
Issue has been created resolving this conversation!

2024-06-12 16:53 UTC, elimanzo commented
Removed local storage calls for #78

2024-06-13 21:58 UTC, abanuelo approved these changes
LGTM!

2024-06-13 22:08 UTC, merged