Feature/league dashboard
cascaritaco/cascarita pull request #77
Opened 2024-06-10 21:57 UTC by jipatino98

### Description

This PR introduces the League Dashboard as well as a reusable component, `DashboardTable`, that will allow developers to create a consistent and styled table to display data in their dashboard. Documentation for this component will be updated in the [Confluence Component Documentation](https://cascarita.atlassian.net/wiki/spaces/~71202069510b02626642319e93c473c7e23d26/pages/32309250/Component+Documentation) file.

This PR also integrated [TanStack Query's](https://tanstack.com/query/latest/docs/framework/react/overview) fetching library that will allow us to, in addition to fetching data from our apis, cache our queries and automatically refresh data when it becomes stale.

### Backend Changes
**In league.controller.js:**
- Originally, if a league_id returns an object with no leagues, the request returns an 505 server error rather than returning a response with no leagues. See the snapshot below to see the changes to the file inside the `if` block.

 
<img width="711" alt="Screenshot 2024-06-10 at 2 20 45 PM" src="https://github.com/cascaritaco/cascarita/assets/120534408/acd7f5e3-f87e-42bc-af62-f9ea16c6bf00">

**In league.route.test.js and group.route.test.js**
- I made some changes to the test suites. Instead of returning an error when there are no leagues for a group_id, it instead expects an empty array.

### Issue Link
- **Create League Dashboard Ticket**
https://cascarita.atlassian.net/browse/C1-87

- **Link "Add League" Button to Leagues Dashboard Ticket**
https://cascarita.atlassian.net/browse/C1-85

### Checklist

- [x] I have tested the changes locally by running `npm run test`
- [x] I have added or updated relevant documentation
- [x] I have autoformatted the code by running `npm run eslint`
- [x] I have added test cases (if applicable)

### Additional Notes

2024-06-10 22:11 UTC, saulRM10 commented on client/components/Forms/LeagueForm.tsx
> +const addLeague = async (formData: object) => {
move api call

2024-06-10 22:16 UTC, abanuelo requested changes
Overall nice work! I learned about query caching! Thanks for making these changes.

2024-06-10 22:16 UTC, abanuelo commented on client/api/teams/types.ts
> +  created_at: string;
I know that on the backend these are official timestamp types, can we preserve that typing on the frontend as well?

2024-06-10 22:16 UTC, abanuelo commented on client/components/Forms/LeagueForm.tsx
> +const addLeague = async (formData: object) => {
Can we add this inside the `client/api` folder?

2024-06-10 22:16 UTC, abanuelo commented on client/components/Forms/LeagueForm.tsx
> +  });
This is just a general question for my understanding. Here when we call `useMutation()`, are we storing the result in a key value dictionary in local memory with the key being `leagues` and the response being the `value`?

2024-06-10 22:16 UTC, abanuelo commented on client/pages/Leagues/Leagues.tsx
> +interface LeaguesProps {
Can we add this Interface into its own `types.ts` file within the directory as the `Leagues.tsx` folder?

2024-06-10 22:16 UTC, abanuelo commented on client/pages/Leagues/Leagues.tsx
> +  const leaguesQuery = useQuery({
For these queries, we also consider storing them within the `client/api` folder.

2024-06-10 22:16 UTC, abanuelo commented on client/pages/Leagues/Leagues.tsx
> +  console.log(currentUser);
nit: remove `console.log`

2024-06-10 22:16 UTC, abanuelo commented on client/pages/Leagues/Leagues.tsx
> +        <p className={styles.noLeagueMessage}>Add a League to Display...</p>
nit: maybe we can push this to another PR, but since our app is now supporting multiple languages, can we make this text follow the convention of other Frontend files to generate both Spanish + English text?

2024-06-14 23:37 UTC, jipatino98 commented on client/components/Forms/LeagueForm.tsx
> +  });
Yeah so `useMutiation` takes in a few option parameters. The ones i used above:
- `mutationFn` is the asynchronous function that returns the promise
- `onSuccess` is one of the various option that tells the React Query that once the mutation is successful (ie the request was successful and the data has been modified), any query with the key `leagues` is refetched and revalidated under the hood.
React Query's hook like `useQuery` and `useMutation` manage all the caching, storing, and refreshing in the background under the hood.

2024-06-14 23:41 UTC, jipatino98 commented on client/pages/Leagues/Leagues.tsx
> +        <p className={styles.noLeagueMessage}>Add a League to Display...</p>
Yes! In the meantime, I can commit what i have. After, we can meet and show me how to use the translation function!

2024-06-15 00:00 UTC, elimanzo requested changes
Good job using React Query! I had some nit feedback and some questions as well

2024-06-15 00:00 UTC, elimanzo commented on client/api/leagues/service.tsx
> +    return result;
you could just return `response.json()`

2024-06-15 00:00 UTC, elimanzo commented on client/components/Forms/LeagueForm/LeagueForm.tsx
> +    leagueFormMutation.mutate({
i think we can delete `newLeague`

and just do 


```
leagueFormMutation.mutate({
      name: leagueName,
      description: leagueDescription,
      group_id: currentUser.group_id,
});
```

2024-06-15 00:00 UTC, elimanzo commented on client/pages/Home/Home.tsx
> +    <div>{currentUser ? <Leagues currentUser={currentUser} /> : <></>}</div>
is we're using a hook for `currentUser` why do we need to prop drill here?

2024-06-15 00:00 UTC, elimanzo commented on server/controllers/league.controller.js
> +      var result = await League.findAll({
`var` makes me assume that we are going to be changing this value outside of the scope. I think changing it to `let` would be suitable here.

2024-06-16 19:45 UTC, jipatino98 commented on client/api/leagues/service.tsx
> +    return result;
Good catch! Resolve that!

2024-06-16 21:57 UTC, jipatino98 commented on client/pages/Home/Home.tsx
> +    <div>{currentUser ? <Leagues currentUser={currentUser} /> : <></>}</div>
You are correct, we dont need to! I will change so that we are calling the hook rather than prop drilling.

2024-06-16 22:11 UTC, jipatino98 commented on client/api/teams/types.ts
> +  created_at: string;
In JavaScript, there isn't a specific timestamp type like in SQL databases, but I can use the `Date` object to handle date and time values. It would look some thing like:
``` javascript
interface Group {
  group_id: number;
  name: string;
  description: string;
  created_at: Date;
} 
```
Then once we fetch the data from the backend, I would just have to make sure to parse the created_at field into a Date object. I will commit the changes, ensuring that `created_at` is a Date object instead.

2024-06-16 22:31 UTC, elimanzo reviewed
Looks good on my end, good job!

2024-06-16 22:31 UTC, elimanzo commented on server/controllers/league.controller.js
> +      let result = await League.findAll({
Looking back at this again, we can just make this a `const`

and just 
`return res.status(200).json(Object.keys(result).length === 0 ? [] : result);`

2024-06-16 22:35 UTC, jipatino98 commented on server/controllers/league.controller.js
> +      let result = await League.findAll({
That actually looks a lot cleaner. I can't remember the reason we used `let` or `var` in the first place, but assuming we are not changing the value anywhere else in the file, `const` does sound like the better declaration. I'll make that change right now. Thank you Eli!

2024-06-18 20:39 UTC, abanuelo approved these changes
Just one nit, but after feel free to merge this pull request looks great!

2024-06-18 20:39 UTC, abanuelo commented on client/api/leagues/service.tsx
> +    const response = await fetch("/api/leagues/", {
nit: remove trailing `/`.

2024-06-18 21:40 UTC, elimanzo approved these changes
Looks Good!

2024-06-18 21:41 UTC, merged