WIP Custom Form
cascaritaco/cascarita pull request #88
Opened 2024-06-26 04:46 UTC by elimanzo

WIP

### Description

### Issue Link

### Checklist

- [ ] I have tested the changes locally by running `npm run test`
- [ ] I have added or updated relevant documentation
- [ ] I have autoformatted the code by running `npm run eslint`
- [ ] I have added test cases (if applicable)

### Additional Notes

2024-06-27 21:31 UTC, JesusGo115 commented on client/App.tsx
> +              <Route path="/form/:formId" element={<FormPage />} />
change /form/:formId to be plural like: "/forms/:formId"
Just to be RESTful

2024-06-27 23:25 UTC, abanuelo requested changes
@elimanzo 💪 great work. A couple of nits, let me know if you have any feedback!

2024-06-27 23:25 UTC, abanuelo commented on client/components/FormInputComponents/LongText/LongText.tsx
> +  };
@elimanzo great work on this event handler. I see that you are recalculating the height based on `scrollHeight` which is fine in theory  since we only ensure the textarea be as tall as needed to fit the content and the content is restricted to a certain size, but should we set maximum height restrictions just in case?
```suggestion
  const handleTextAreaChange = (
  event: React.ChangeEvent<HTMLTextAreaElement>,
  initialHeight: string = "auto",
  maxHeight: string = "500px" // Set a maximum height
) => {
  setTextAreaValue(event.target.value);
  const textArea = event.target;
  textArea.style.height = initialHeight;
  textArea.style.height = `${textArea.scrollHeight}px`;
  if (textArea.scrollHeight > parseInt(maxHeight)) {
    textArea.style.height = maxHeight;
  }
  registerOnChange(event);
};
```

2024-06-27 23:25 UTC, abanuelo commented on client/components/FormInputComponents/PhoneNumber/PhoneNumber.tsx
> +            value: /^\+?[1-9]\d{1,14}$/,
The placeholder that you for the `<input />` cannot be accepted by the regex. Users may follow the placeholder code and may be confused as to why its not getting accepted! Consider updating the regex to match the following:
```suggestion
            value: /(\+?\d{1,3})?[-.\s]?(\(?\d{1,4}\)?)?[-.\s]?\d{1,4}[-.\s]?\d{1,4}[-.\s]?\d{1,9}/
,
```

2024-06-27 23:25 UTC, abanuelo commented on client/pages/FormPage/FormPage.tsx
> +    console.log(normalizedAnswers);
nit: remove console log

2024-06-27 23:25 UTC, abanuelo commented on client/pages/FormPage/FormPage.tsx
> +  const AnswerMap = {
`AnswerMap` and `FieldComponents` below aren't types or interfaces and I get why they weren't added to the `./types.ts` file. However, they seem to be heavily reliant on the types and interfaces defined in `types.ts`. Consider just adding them directly within the `types.ts` file. Up to you though!

2024-06-28 17:48 UTC, elimanzo commented on client/components/FormInputComponents/LongText/LongText.tsx
> +  };
Good call!

2024-06-28 19:49 UTC, abanuelo approved these changes
All, in all everything looks great. Thanks for the `StrictModeDroppable` workaround. Looks great!

2024-06-28 19:51 UTC, merged