feat: Brevo Email Integration To Share Forms
cascaritaco/cascarita pull request #89
Opened 2024-06-26 05:32 UTC by abanuelo

### Description

Adding email integration based on design. Below is video illustrating the changes:

https://github.com/cascaritaco/cascarita/assets/32311654/0f04c096-7446-41ed-a1ac-b367ac52c5a0

### Issue Link

[Jira Ticket - C1-103](https://cascarita.atlassian.net/jira/software/c/projects/C1/boards/2/backlog?selectedIssue=C1-103&atlOrigin=eyJpIjoiNDAzOThjZTZmMjFhNGQ2OThmODRlOGVlYjY4YTlmZjMiLCJwIjoiaiJ9)

### Checklist

- [X] I have tested the changes locally by running `npm run test`
- [ ] I have added or updated relevant documentation
- [ ] I have autoformatted the code by running `npm run eslint`
- [ ] I have added test cases (if applicable)

### Additional Notes

2024-06-26 07:23 UTC, elimanzo requested changes
Hey @abanuelo this is really cool! I have a small nit, but other than that good job!

2024-06-26 20:31 UTC, abanuelo commented on client/pages/Forms/Forms.tsx
> +                setOpen={setOpen}
Gotcha! Also look what I saw on my daily.dev newsletter today: https://app.daily.dev/posts/PMBIEyN9J?utm_source=notification&utm_medium=email&utm_campaign=digest
It's like there are signs from the universe or something 🙃

2024-06-26 20:33 UTC, elimanzo commented on client/pages/Forms/Forms.tsx
> +                setOpen={setOpen}
😂 i promise I didn't write that newsletter.

2024-06-27 23:46 UTC, abanuelo commented on client/pages/Forms/Forms.tsx
> +                setOpen={setOpen}
Resolved!

2024-06-28 19:59 UTC, elimanzo requested changes
I just have a couple of nits, and I think we're good to go 😄

2024-06-28 19:59 UTC, elimanzo commented on client/pages/Forms/Forms.tsx
> +  const handleOpenChange = (isOpen: boolean) => {
I think we can get rid of the intermediate variables and just have it as such 

```Typescript
const ShareModal: React.FC<ShareModalProps> = ({ formLink, isOpen, onOpen }) => {
  return (
    <Modal open={isOpen} onOpenChange={onOpen}>
      <Modal.Button asChild className={styles.btn}>
        <button onClick={() => onOpen(true)}>
          <ShareButton />
        </button>
      </Modal.Button>
      <Modal.Content title="Share Form">
        <ShareForm afterClose={() => onOpen(false)} formLink={formLink} />
      </Modal.Content>
    </Modal>
  );
};
```

2024-06-28 19:59 UTC, elimanzo commented on client/pages/Forms/Forms.tsx
> +const ShareModal: React.FC<ShareModalProps> = ({ formLink, open, onOpen }) => {
looking at the variable names, probably best to call `open` to `isOpen`

2024-06-28 19:59 UTC, elimanzo commented on client/pages/Forms/Forms.tsx
> +  const [open, setOpen] = useState(false);
same as above calling `isOpen` and `setIsOpen`

2024-06-28 19:59 UTC, elimanzo commented on client/pages/Forms/Forms.tsx
> +                onOpen={(open: boolean) => setOpen(open)}
same thing as above calling `isOpen`

2024-06-28 23:35 UTC, abanuelo commented on client/pages/Forms/Forms.tsx
> +const ShareModal: React.FC<ShareModalProps> = ({ formLink, open, onOpen }) => {
Ack! Done!

2024-06-28 23:35 UTC, abanuelo commented on client/pages/Forms/Forms.tsx
> +  const [open, setOpen] = useState(false);
Ack! Done!

2024-06-28 23:36 UTC, abanuelo commented on client/pages/Forms/Forms.tsx
> +                onOpen={(open: boolean) => setOpen(open)}
Ack! Done!

2024-06-28 23:36 UTC, abanuelo commented on client/pages/Forms/Forms.tsx
> +  const handleOpenChange = (isOpen: boolean) => {
Ack! Done!

2024-06-29 00:21 UTC, elimanzo approved these changes
LGTM!

2024-06-29 00:22 UTC, merged