Feat: Create Response Endpoint
cascaritaco/cascarita pull request #93
Opened 2024-07-05 21:51 UTC by JesusGo115

### Description

Added the createResponse endpoint to insert responses into the MongoDB and updated the getResponses endpoint to retrieve all the responses from the MongoDB

### Checklist

- [x] I have tested the changes locally by running `npm run test`
- [ ] I have added or updated relevant documentation
- [x] I have autoformatted the code by running `npm run eslint`
- [ ] I have added test cases (if applicable)

2024-07-05 22:54 UTC, abanuelo requested changes
Overall good stuff! Just a minor comment. Also maybe make an issue for this for future reference but `/:form_id/responses` should ideally be paginated so that we don't return too many responses all at once from a league. For now, this looks good!

2024-07-05 22:54 UTC, abanuelo commented on server/utilityFunctions/responseParser.js
> +// ** DEPRECATED **
nit: but why is this deprecated, I am fine leaving the comment here but giving some more context as to why that is would be helpful!

2024-07-06 00:23 UTC, saulRM10 commented on server/controllers/form.controller.js
>  const jsonParser = require("../utilityFunctions/responseParser");
remove this if you not using it no more

2024-07-06 00:23 UTC, saulRM10 approved these changes
Over all looks good

2024-07-06 00:24 UTC, saulRM10 commented on server/utilityFunctions/responseParser.js
> +// ** DEPRECATED **
if depreciated,  should we just get rid of the file @garcialuis ?

2024-07-06 02:21 UTC, JesusGo115 commented on server/utilityFunctions/responseParser.js
> +// ** DEPRECATED **
Hey Armando, this file is deprecated since it was primarily used for the endpoints that dealt with Typeform. Since we're no longer using Typeform, this file and its functions aren't needed at the moment. I wasn't too sure if I should delete it, it might deem useful later, but we'll wait for @garcialuis and see what he thinks.

2024-07-06 02:21 UTC, JesusGo115 commented on server/controllers/form.controller.js
>  const jsonParser = require("../utilityFunctions/responseParser");
Removed!

2024-07-06 02:42 UTC, elimanzo requested changes
looks good just couple of nit 😃

2024-07-06 02:42 UTC, elimanzo commented on client/pages/FormPage/FormPage.tsx
> +    console.log(normalizedAnswers);
lets remove console log.

2024-07-06 02:42 UTC, elimanzo commented on client/pages/FormPage/FormPage.tsx
> +      "testFormId",
don't need to pass this string, form's page already takes in the formId, so you can just pass in `formId`

2024-07-06 02:49 UTC, JesusGo115 commented on client/pages/FormPage/FormPage.tsx
> +      "testFormId",
Changed!

2024-07-06 02:49 UTC, JesusGo115 commented on client/pages/FormPage/FormPage.tsx
> +    console.log(normalizedAnswers);
Removed!

2024-07-06 04:01 UTC, JesusGo115 commented on server/utilityFunctions/responseParser.js
> +// ** DEPRECATED **
Deleted the file!

2024-07-06 04:11 UTC, elimanzo approved these changes
LGTM Good job!

2024-07-08 21:15 UTC, abanuelo commented on server/controllers/form.controller.js
> +    } catch (error) {
should we have a `console.error()` here?

2024-07-08 21:15 UTC, abanuelo approved these changes

2024-07-08 21:50 UTC, JesusGo115 commented on client/pages/FormPage/FormPage.tsx
> +    const responsesData = await createMongoResponse(
Added a try/catch to this

2024-07-08 21:55 UTC, JesusGo115 commented on server/controllers/form.controller.js
> +    } catch (error) {
The middleware has the console.error() and the next(error) triggers the middleware.

2024-07-08 22:01 UTC, merged