Poc/set up stripe
cascaritaco/cascarita pull request #95
Opened 2024-07-07 19:18 UTC by saulRM10

### Description

### Issue Link

### Checklist

- [ ] I have tested the changes locally by running `npm run test`
- [ ] I have added or updated relevant documentation
- [ ] I have autoformatted the code by running `npm run eslint`
- [ ] I have added test cases (if applicable)

### Additional Notes

2024-07-12 23:09 UTC, JesusGo115 commented on client/pages/Forms/Forms.tsx
> +        <ConnectWithStripeButton />
I'm not 100% sure if this is the cause, but due to the changes, it doesn't allow you to open the form to submit a response

2024-07-12 23:14 UTC, JesusGo115 commented on server/controllers/account.controller.js
> +      console.log(stripeAccountId);
remove the console.log

2024-07-12 23:18 UTC, JesusGo115 commented on server/models/form.js
> +        targetKey: "id",
Should be sourcekey instead of targetkey

2024-07-12 23:46 UTC, JesusGo115 requested changes
Overall, looks good, but there are some issues that need to be fixed

2024-07-19 22:17 UTC, saulRM10 commented on client/pages/Forms/Forms.tsx
> +        <ConnectWithStripeButton />
It's not due to the stripe button component

2024-07-26 00:22 UTC, JesusGo115 approved these changes
Looks good!

2024-07-26 17:18 UTC, merged