[WIP] fix: docker deployments to ecs
cascaritaco/cascarita pull request #98
Opened 2024-07-22 21:45 UTC by abanuelo

### Description

Looking to change some of the format for Docker files present in our repo to facilitate deployment!

### Issue Link

### Checklist

- [ ] I have tested the changes locally by running `npm run test`
- [ ] I have added or updated relevant documentation
- [ ] I have autoformatted the code by running `npm run eslint`
- [ ] I have added test cases (if applicable)

### Additional Notes

2024-08-15 02:13 UTC, alexrdrgz reviewed
Small optimizations but looks like a good refactor

Note: did not test the container

2024-08-15 02:13 UTC, alexrdrgz commented on docker-compose.yml
>        - "3001:3001"
You can do the same things here

2024-08-15 02:13 UTC, alexrdrgz commented on docker-compose.yml
> -      - .:/app
You may want to decouple the volumes when deploying to production by using named volumes. 

I don't know the full context of the project but if you want the data to persist when containers are restarted or not you'd want to take that path

2024-08-15 02:22 UTC, alexrdrgz commented on client/Dockerfile
> +COPY ./package.json ./package-lock.json ./webpack.config.js /.env ./
Ultra nit picky but you can optimize this to not include the build tools when deploying to production.

Makes it slightly leaner and more secure

2024-08-15 02:26 UTC, alexrdrgz commented on client/Dockerfile
> +COPY ./package.json ./package-lock.json ./webpack.config.js /.env ./
meant to comment this on the server

2024-08-15 20:52 UTC, abanuelo commented on docker-compose.yml
>        - "3000:3000"
Thanks for this! We definitely want a way to sync with the `env` file values since that is going to be the source of truth!

2024-08-15 20:53 UTC, abanuelo commented on docker-compose.yml
>        - "3001:3001"
Wait, can you elaborate by what you mean "same things here"?

2024-08-15 20:53 UTC, abanuelo commented on client/Dockerfile
> +COPY ./package.json ./package-lock.json ./webpack.config.js /.env ./
Gotcha, let me try to remove that from the server Docker file so that can make it leaner and more secure thanks for the feedback!

2024-09-25 01:20 UTC, garcialuis requested changes

2024-09-25 01:20 UTC, garcialuis commented on server/Dockerfile
> +EXPOSE 3306
We can remove this line, we should not expose port 3306 from the server container

2024-09-25 01:20 UTC, garcialuis commented on docker-compose.yml
>        - "3306:3306"
We should also remove port 3306 from the docker-compose file

2024-09-25 03:49 UTC, abanuelo commented on docker-compose.yml
>        - "3001:3001"
Ack! I have resolved the communication update here! Closing out the PR!

2024-09-25 03:51 UTC, abanuelo commented on server/Dockerfile
> +EXPOSE 3306
Ack! Done!

2024-09-25 03:51 UTC, abanuelo commented on docker-compose.yml
>        - "3306:3306"
Ack! Done!

2024-09-25 04:53 UTC, garcialuis approved these changes
Thanks for making those changes Armando, LGTM

2024-09-25 04:55 UTC, merged